services:
  subscription-service:
    build:
      context: .
      target: ${TARGET:-develop}
    image: ${IMAGE:-subscription-service}
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    environment:
      ADOBE_API_URL: http://fake
      SESSION_UPDATED_WEBHOOK_URL: http://consumer1;http://consumer2;http://consumer3
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
  database:
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - '8000:8080'
volumes:
  pgdata:
    driver: local
