services:
  subscription-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/subscription_db
      - SESSION_UPDATED_WEBHOOK_URL=http://webhook-url
    depends_on:
      - mysql

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: subscription_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
